# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocb < Formula
  desc "This program generates a custom OpenTelemetry Collector from a given configuration."
  homepage "https://opentelemetry.io/docs/collector/custom-collector/"
  version "1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.0/ocb_1.0_darwin_arm64"
      sha256 "8cb8a089f9af6efb8ca03bd081c86c5a70aa9ad546ef95456fa4f52c52a9e06e"

      def install
        bin.install "ocb_1.0_darwin_arm64" => "ocb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.0/ocb_1.0_darwin_amd64"
      sha256 "6bcae4aff09fbe276d94d0c3eb99beb90dc92cc01eb14e6b65200738e5def768"

      def install
        bin.install "ocb_1.0_darwin_amd64" => "ocb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.0/ocb_1.0_linux_arm64"
      sha256 "60e372c4f1c7b4655dc232ba6cc33a416e23177b53d5368eebbc7829f5b7d8ac"

      def install
        bin.install "ocb_1.0_linux_arm64" => "ocb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.0/ocb_1.0_linux_amd64"
      sha256 "422ae06e5bc201bfba18b6db24a818190d43bf7278f0f0e01da20f24eea62425"

      def install
        bin.install "ocb_1.0_linux_amd64" => "ocb"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/ocb version"
  end
end
