# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocb < Formula
  desc "This program generates a custom OpenTelemetry Collector from a given configuration."
  homepage "https://opentelemetry.io/docs/collector/custom-collector/"
  version "1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.1/ocb_1.1_darwin_amd64"
      sha256 "2f9f0fbb64968821e3f92ae90bcafd4bbae41e503e01829ca9ea81d60afeb43a"

      def install
        bin.install "ocb_1.1_darwin_amd64" => "ocb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.1/ocb_1.1_darwin_arm64"
      sha256 "6e710d0f2fdde4b8b5f3bd0ad5892197742ceb770e0baebcaa4522cf3a2e9bf0"

      def install
        bin.install "ocb_1.1_darwin_arm64" => "ocb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.1/ocb_1.1_linux_amd64"
      sha256 "47e4fd710f0d2986988b94e0c982714d7763ba09de2cdd31bcbdbf36d9baafc4"

      def install
        bin.install "ocb_1.1_linux_amd64" => "ocb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpeach/homebrew-tap/releases/download/v1.1/ocb_1.1_linux_arm64"
      sha256 "93005b8b835dfbee5e05f5f0d67492e02b78ccf3985fa85c685022c28de48e46"

      def install
        bin.install "ocb_1.1_linux_arm64" => "ocb"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/ocb version"
  end
end
